export const GET_TODO_REQ = "GET_TODO_REQ";
export const GET_TODO_SUCC = "GET_TODO_SUCC";
export const GET_TODO_FAIL = "GET_TODO_FAIL";

export const POST_TODO_REQ = "POST_TODO_REQ";
export const POST_TODO_SUCC = "POST_TODO_SUCC";
export const POST_TODO_FAIL = "POST_TODO_FAIL";

export const PATCH_TODO_REQ = "PATCH_TODO_REQ";
export const PATCH_TODO_SUCC = "PATCH_TODO_SUCC";
export const PATCH_TODO_FAIL = "PATCH_TODO_FAIL";

export const DELETE_TODO_REQ = "DELETE_TODO_REQ";
export const DELETE_TODO_SUCC = "DELETE_TODO_SUCC";
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

export const EDIT_TODO_SUCC = "EDIT_TODO_SUCC";

export const COMPLETED_TODO_SUCC = "COMPLETED_TODO_SUCC";
